blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://cadhy.dev/docs
    about: Check our documentation before opening an issue
  - name: Discussions
    url: https://github.com/nicofrem/CADHY/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
